version: '3'

services:

  postgres.yang.dev.br:
    image: postgres:15.3-alpine3.18    
    container_name: postgres.yang.dev.br
    hostname: postgres.yang.dev.br
    restart: unless-stopped
    command: -p $POSTGRES_PORT
    ports:
      - '$POSTGRES_PORT:$POSTGRES_PORT'
    volumes:
      - .databases/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env

  api.yang.dev.br:
    build:
      context: .
      dockerfile: Dockerfile
    image: yang.dev.br/api
    hostname: api.yang.dev.br
    container_name: api.yang.dev.br
    tty: true
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000